import { SeancePC } from "./types";

export const INITIAL_SEANCES: SeancePC[] = [
  {
    id: "seance-1",
    titre: "CNC 2024 (MP) — Induction, courants de Foucault et freinage électromagnétique",
    module: "Électromagnétisme",
    type: "Concours",
    concoursName: "CNC",
    date: "24 Septembre 2026",
    description: "Étude complète du problème CNC MP 2024 : couplage électromécanique, bilan d'énergie de Poynting et modélisation des courants induits.",
    enonceUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
    corrigeUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    isPinned: true,
  },
  {
    id: "seance-2",
    titre: "Mines-Ponts 2023 — Transferts thermiques et diffusion de la chaleur en géométrie cylindrique",
    module: "Thermodynamique",
    type: "Concours",
    concoursName: "Mines-Ponts",
    date: "20 Septembre 2026",
    description: "Résolution de l'équation de Fourier stationnaire et instationnaire, ailettes de refroidissement et résistance thermique de contact.",
    enonceUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
    corrigeUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "seance-3",
    titre: "Cours & TD Méthode — Équations de Maxwell dans le vide et en milieu conducteur",
    module: "Électromagnétisme",
    type: "Cours",
    date: "17 Septembre 2026",
    description: "Synthèse des théorèmes intégraux, passage aux conditions aux limites, épaisseur de peau et propagation des ondes guidées.",
    enonceUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
    corrigeUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
  },
  {
    id: "seance-4",
    titre: "CCINP 2024 — Interférences à deux ondes & Dispositif de Michelson en coin d'air",
    module: "Optique Ondulatoire",
    type: "Concours",
    concoursName: "CCINP",
    date: "12 Septembre 2026",
    description: "Analyse des franges d'égale épaisseur, localisation des franges, influence de la cohérence spatiale et mesure de variations nanométriques.",
    enonceUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
    corrigeUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "seance-5",
    titre: "Diagrammes d'Ellingham et pyrométallurgie du Titane et du Fer",
    module: "Chimie des Solutions",
    type: "TD & Exercices",
    date: "08 Septembre 2026",
    description: "Approximation d'Ellingham, corrosion sèche des métaux, domaines de prédominance et calcul des températures de réduction sous vide.",
    enonceUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
    corrigeUrl: "https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs/preview",
  },
];
